service: star-wars-challenge

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt CharactersTable.Arn

package:
  patterns:
    - '!node_modules/serverless-dynamodb-local/**'
    - '!node_modules/aws-sdk/**'
    - '!test/**'
    - '!.git/**'
    - '!.vscode/**'
    - '!.serverless/**'
    - '!*.test.ts'
    - '!jest.config.js'
    - '!tsconfig.json'
    - '!README.md'
    - '!.eslintrc.js'
    - '!.prettierrc'

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          path: /api/v1/{proxy+}
          method: ANY
    environment:
      CACHE_TTL: 1800 # 30 minutes in seconds

resources:
  Resources:
    CharactersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-characters
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
